### ISSUE TITLE
Cannot fetch remote documentation: internal error

### ISSUE THREAD

**Issue by peterkolski** [EddieRingle/clion-cmakedocs#1]
No documentation appears, but this message instead
`Cannot fetch remote documentation: internal error`

**Comment by max-bondarenko** [comment]
Same: 
On request documentation in command e.g. find_package() 

```
2017-08-03 18:32:57,501 [  17481]   INFO - mentation.DocumentationManager - org.asciidoc.intellij.AsciiDoc.<init>(Ljava/io/File;)V 
java.lang.NoSuchMethodError: org.asciidoc.intellij.AsciiDoc.<init>(Ljava/io/File;)V
	at CMakeDocProvider$asciiDoc$2.invoke(CMakeDocProvider.kt:23)
	at CMakeDocProvider$asciiDoc$2.invoke(CMakeDocProvider.kt:15)
	at kotlin.SynchronizedLazyImpl.getValue(Lazy.kt:130)
	at CMakeDocProvider.getAsciiDoc(CMakeDocProvider.kt)
	at CMakeDocProvider.generateDoc(CMakeDocProvider.kt:79)
	at com.intellij.lang.documentation.CompositeDocumentationProvider.generateDoc(CompositeDocumentationProvider.java:144)
	at com.intellij.codeInsight.documentation.DocumentationManager$DefaultDocumentationCollector.a(DocumentationManager.java:1136)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1161)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:90)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:146)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:548)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)

**Comment by airfield20** [comment]
This issue is still present
